rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ree
  - jruby

gemfile:
  - gemfiles/rails_3_0.gemfile
  - gemfiles/rails_3_1.gemfile
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: ree
      gemfile: gemfiles/rails_4_0.gemfile