rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.3
  - ree
  - jruby

gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile

matrix:
  exclude:
    - rvm: ree
      gemfile: gemfiles/rails_4_0.gemfile
      gemfile: gemfiles/rails_4_1.gemfile
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5_0.gemfile
